# New in floodstate-eo, 2026-10-01 (maintainer: "why does this go in circles, why never the full picture"). STATUS: ACTIVE.
"""p96b -- the full picture of the reed-bed question on one page, generated from the publication tables so that it cannot drift:
publication/WETLAND_EVIDENCE.md. Every number is a placeholder resolved against publication/tables (fill_manuscript.make_resolver,
as T28); the evidence-availability matrix comes from T01b (p95u); the maps are listed only if the files exist; the cells that are
empty say why. Run after p96."""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
CS = HERE.parents[1]; PUB = CS / "publication"; PT = PUB / "tables"; FIG = CS / "figures" / "m6_v003A"
MIN_SHARE = 0.5


def _ld(name, path):
    s = importlib.util.spec_from_file_location(name, path); m = importlib.util.module_from_spec(s); s.loader.exec_module(m)
    return m


H = lambda d, r, g, c, f=".0f": "{{T12h|date=" + d + ",region=" + r + ",ground=" + g + "|" + c + "||" + f + "}}"
J = lambda z, st, c, f=".2f": "{{T12j|zone=" + z + ",stratum=" + st + "|" + c + "||" + f + "}}"
B = lambda g, c, f=".2f": "{{T16b|region=corridor + Inhulets,ground=" + g + "|" + c + "||" + f + "}}"
K = lambda g, c, f=".2f": "{{T16c|ground=" + g + "|" + c + "||" + f + "}}"
C, CI = "DNIPRO_CORRIDOR", "DNIPRO_CORRIDOR+INHULETS_VALLEY_rect"
WET, DRY = "vegetated wetland", "dry-before-event ground"

TEMPLATE = f"""# The reed-bed question: the full picture

Generated by `workflows/paper/p96b_wetland_evidence.py` from the publication tables of this build — do not edit by hand.
The question: how much of the June 2023 inundation was new flooding of dry ground, and what was the vegetated wetland
(reed beds of the Kherson delta and of the floodway between the dam and Kherson) before the breach. Three pre-event ground
classes (p95x `ground_class.tif`): dry before the event / seasonally wet vegetated wetland / open reference water.

## 1. What each sensor observed (T01b, p95u) — the gate of every diagnostic

Share of the stratum with at least one clear observation in the period (ALL = every domain cell of the zone; the wetland class
alone follows). Cells below {MIN_SHARE:.0%} are the reason a period is mapped with another sensor or not at all.

{{{{MATRIX_ALL}}}}

Vegetated wetland only:

{{{{MATRIX_WETLAND}}}}

Empty or weak cells and why:

{{{{GAPS}}}}

## 2. The quantities (T12h; coherent Monte-Carlo worlds of p95e, median [p05–p95], nominal world in brackets)

| quantity | corridor 7 June | corridor + Inhulets 7 June | corridor 8 June | corridor 13 June |
|---|---|---|---|---|
| A_new,dry — new inundation of dry ground, km² | {H('2023-06-07', C, 'dry_before_event', 'new_km2_p50')} [{H('2023-06-07', C, 'dry_before_event', 'new_km2_p05')}–{H('2023-06-07', C, 'dry_before_event', 'new_km2_p95')}] ({H('2023-06-07', C, 'dry_before_event', 'new_km2_nominal')}) | {H('2023-06-07', CI, 'dry_before_event', 'new_km2_p50')} [{H('2023-06-07', CI, 'dry_before_event', 'new_km2_p05')}–{H('2023-06-07', CI, 'dry_before_event', 'new_km2_p95')}] | {H('2023-06-08', C, 'dry_before_event', 'new_km2_p50')} [{H('2023-06-08', C, 'dry_before_event', 'new_km2_p05')}–{H('2023-06-08', C, 'dry_before_event', 'new_km2_p95')}] | {H('2023-06-13', C, 'dry_before_event', 'new_km2_p50')} [{H('2023-06-13', C, 'dry_before_event', 'new_km2_p05')}–{H('2023-06-13', C, 'dry_before_event', 'new_km2_p95')}] |
| A_wet — wetland inside the event extent, km² | {H('2023-06-07', C, 'vegetated_wetland', 'water_km2_p50')} [{H('2023-06-07', C, 'vegetated_wetland', 'water_km2_p05')}–{H('2023-06-07', C, 'vegetated_wetland', 'water_km2_p95')}] ({H('2023-06-07', C, 'vegetated_wetland', 'water_km2_nominal')}) | {H('2023-06-07', CI, 'vegetated_wetland', 'water_km2_p50')} | {H('2023-06-08', C, 'vegetated_wetland', 'water_km2_p50')} | {H('2023-06-13', C, 'vegetated_wetland', 'water_km2_p50')} |
| A_wet on 5 June (reconstructed pre-breach state), km² | {H('2023-06-05', C, 'vegetated_wetland', 'water_km2_p50')} [{H('2023-06-05', C, 'vegetated_wetland', 'water_km2_p05')}–{H('2023-06-05', C, 'vegetated_wetland', 'water_km2_p95')}] ({H('2023-06-05', C, 'vegetated_wetland', 'water_km2_nominal')}) | {H('2023-06-05', CI, 'vegetated_wetland', 'water_km2_p50')} | — | — |
| ΔA_wet — event increase over 5 June, km² (baseline-dependent) | {H('2023-06-07', C, 'vegetated_wetland', 'water_increase_km2_p50')} [{H('2023-06-07', C, 'vegetated_wetland', 'water_increase_km2_p05')}–{H('2023-06-07', C, 'vegetated_wetland', 'water_increase_km2_p95')}] ({H('2023-06-07', C, 'vegetated_wetland', 'water_increase_km2_nominal')}) | {H('2023-06-07', CI, 'vegetated_wetland', 'water_increase_km2_p50')} [{H('2023-06-07', CI, 'vegetated_wetland', 'water_increase_km2_p05')}–{H('2023-06-07', CI, 'vegetated_wetland', 'water_increase_km2_p95')}] | {H('2023-06-08', C, 'vegetated_wetland', 'water_increase_km2_p50')} | {H('2023-06-13', C, 'vegetated_wetland', 'water_increase_km2_p50')} |
| A_new (all ground; the headline of T12), km² | {H('2023-06-07', C, 'all', 'new_km2_p50')} [{H('2023-06-07', C, 'all', 'new_km2_p05')}–{H('2023-06-07', C, 'all', 'new_km2_p95')}] ({H('2023-06-07', C, 'all', 'new_km2_nominal')}) | {H('2023-06-07', CI, 'all', 'new_km2_p50')} | {H('2023-06-08', C, 'all', 'new_km2_p50')} | {H('2023-06-13', C, 'all', 'new_km2_p50')} |

Semantics: A_wet is the event extent over the wetland (robust across worlds); ΔA_wet is a difference from the reconstructed
5 June state and inherits its uncertainty (the nominal world lies outside the interval). Never add A_wet or ΔA_wet to A_new,dry.

## 3. The pre-event state of the wetland (T12j, p95z; stratum medians, nothing fitted)

| zone | stratum | NDVI Jun 2022 | MNDWI Jun 2022 | last S2 before the breach | MNDWI then | S1 VV spring 2023, dB | VV − VH, dB |
|---|---|---|---|---|---|---|---|
| delta | normally-wet reeds | {J('delta', 'NW_REEDS', 'S2_jun2022_NDVI')} | {J('delta', 'NW_REEDS', 'S2_jun2022_MNDWI')} | {{{{T12j|zone=delta,stratum=NW_REEDS|S2_last_pre_date||}}}} | {J('delta', 'NW_REEDS', 'S2_last_pre_MNDWI')} | {J('delta', 'NW_REEDS', 'S1_spring2023_VV_dB', '.1f')} | {J('delta', 'NW_REEDS', 'S1_spring2023_VV_minus_VH_dB', '.1f')} |
| delta | reeds reached only by the event | {J('delta', 'EVENT_REEDS', 'S2_jun2022_NDVI')} | {J('delta', 'EVENT_REEDS', 'S2_jun2022_MNDWI')} | {{{{T12j|zone=delta,stratum=EVENT_REEDS|S2_last_pre_date||}}}} | {J('delta', 'EVENT_REEDS', 'S2_last_pre_MNDWI')} | {J('delta', 'EVENT_REEDS', 'S1_spring2023_VV_dB', '.1f')} | {J('delta', 'EVENT_REEDS', 'S1_spring2023_VV_minus_VH_dB', '.1f')} |
| delta | reeds above the reach of the flood | {J('delta', 'HIGH_REEDS', 'S2_jun2022_NDVI')} | {J('delta', 'HIGH_REEDS', 'S2_jun2022_MNDWI')} | {{{{T12j|zone=delta,stratum=HIGH_REEDS|S2_last_pre_date||}}}} | {J('delta', 'HIGH_REEDS', 'S2_last_pre_MNDWI')} | {J('delta', 'HIGH_REEDS', 'S1_spring2023_VV_dB', '.1f')} | {J('delta', 'HIGH_REEDS', 'S1_spring2023_VV_minus_VH_dB', '.1f')} |
| delta | dry ground | {J('delta', 'DRY_LAND', 'S2_jun2022_NDVI')} | {J('delta', 'DRY_LAND', 'S2_jun2022_MNDWI')} | {{{{T12j|zone=delta,stratum=DRY_LAND|S2_last_pre_date||}}}} | {J('delta', 'DRY_LAND', 'S2_last_pre_MNDWI')} | {J('delta', 'DRY_LAND', 'S1_spring2023_VV_dB', '.1f')} | {J('delta', 'DRY_LAND', 'S1_spring2023_VV_minus_VH_dB', '.1f')} |
| floodway | normally-wet reeds | {J('floodway', 'NW_REEDS', 'S2_jun2022_NDVI')} | {J('floodway', 'NW_REEDS', 'S2_jun2022_MNDWI')} | {{{{T12j|zone=floodway,stratum=NW_REEDS|S2_last_pre_date||}}}} | {J('floodway', 'NW_REEDS', 'S2_last_pre_MNDWI')} | {J('floodway', 'NW_REEDS', 'S1_spring2023_VV_dB', '.1f')} | {J('floodway', 'NW_REEDS', 'S1_spring2023_VV_minus_VH_dB', '.1f')} |
| floodway | reeds reached only by the event | {J('floodway', 'EVENT_REEDS', 'S2_jun2022_NDVI')} | {J('floodway', 'EVENT_REEDS', 'S2_jun2022_MNDWI')} | {{{{T12j|zone=floodway,stratum=EVENT_REEDS|S2_last_pre_date||}}}} | {J('floodway', 'EVENT_REEDS', 'S2_last_pre_MNDWI')} | {J('floodway', 'EVENT_REEDS', 'S1_spring2023_VV_dB', '.1f')} | {J('floodway', 'EVENT_REEDS', 'S1_spring2023_VV_minus_VH_dB', '.1f')} |
| floodway | reeds above the reach of the flood | {J('floodway', 'HIGH_REEDS', 'S2_jun2022_NDVI')} | {J('floodway', 'HIGH_REEDS', 'S2_jun2022_MNDWI')} | {{{{T12j|zone=floodway,stratum=HIGH_REEDS|S2_last_pre_date||}}}} | {J('floodway', 'HIGH_REEDS', 'S2_last_pre_MNDWI')} | {J('floodway', 'HIGH_REEDS', 'S1_spring2023_VV_dB', '.1f')} | {J('floodway', 'HIGH_REEDS', 'S1_spring2023_VV_minus_VH_dB', '.1f')} |
| floodway | dry ground | {J('floodway', 'DRY_LAND', 'S2_jun2022_NDVI')} | {J('floodway', 'DRY_LAND', 'S2_jun2022_MNDWI')} | {{{{T12j|zone=floodway,stratum=DRY_LAND|S2_last_pre_date||}}}} | {J('floodway', 'DRY_LAND', 'S2_last_pre_MNDWI')} | {J('floodway', 'DRY_LAND', 'S1_spring2023_VV_dB', '.1f')} | {J('floodway', 'DRY_LAND', 'S1_spring2023_VV_minus_VH_dB', '.1f')} |

Reading: no optical water on the reed beds in a normal June nor in the last scene before the breach; a C-band double-bounce
signature on the low reed beds (normally wet and event-only alike in the delta) that dry-footed reeds and dry ground lack —
consistent with wet or inundated emergent vegetation, establishing neither open water nor a depth, stratum-level, never a map of
water on 5 June. Full windows (peak, recession) in T12i; class shares of the composites in T12k–T12m.

## 4. Diagnostic comparison with UNOSAT (T16b, T16c; not validation — UNOSAT shaped earlier fixes)

| ground class | cumulative 6–9 June: UNOSAT share / ours | CSI | CSI by chance | Heidke | UNOSAT-only km² (of which ours UNKNOWN / EO-dry / model-dry) | ours-only km² |
|---|---|---|---|---|---|---|
| dry before the event | {B(DRY, 'UNOSAT_share_of_ground', '.0%')} / {B(DRY, 'ours_share_of_ground', '.0%')} | {B(DRY, 'CSI')} | {B(DRY, 'CSI_chance')} | {B(DRY, 'heidke_skill')} | {B(DRY, 'UNOSAT_only_km2', '.0f')} ({B(DRY, 'UNOSAT_only_where_ours_UNKNOWN_km2', '.0f')} / {B(DRY, 'UNOSAT_only_where_ours_EO_dry_km2', '.0f')} / {B(DRY, 'UNOSAT_only_where_ours_model_dry_km2', '.0f')}) | {B(DRY, 'ours_only_km2', '.0f')} |
| vegetated wetland | {B(WET, 'UNOSAT_share_of_ground', '.0%')} / {B(WET, 'ours_share_of_ground', '.0%')} | {B(WET, 'CSI')} | {B(WET, 'CSI_chance')} | {B(WET, 'heidke_skill')} | {B(WET, 'UNOSAT_only_km2', '.0f')} ({B(WET, 'UNOSAT_only_where_ours_UNKNOWN_km2', '.0f')} / {B(WET, 'UNOSAT_only_where_ours_EO_dry_km2', '.0f')} / {B(WET, 'UNOSAT_only_where_ours_model_dry_km2', '.0f')}) | {B(WET, 'ours_only_km2', '.0f')} |

7 June against the ICEYE-based layer (T16c): dry ground CSI {K(DRY, 'CSI_decided')} on {K(DRY, 'coverage', '.0%')} decided cells,
admissible interval {K(DRY, 'CSI_min')}–{K(DRY, 'CSI_max')}, {K(DRY, 'ICEYE_water_in_UNKNOWN_share', '.0%')} of the ICEYE water in
our UNKNOWN; wetland CSI {K(WET, 'CSI_decided')} on {K(WET, 'coverage', '.0%')} decided, interval {K(WET, 'CSI_min')}–{K(WET, 'CSI_max')}.
Reading: the flood boundary is tested on the dry ground (CSI far above chance); over the wetland a high CSI is largely prevalence
— the reconstruction places the wetland inside the event extent without contradicting UNOSAT, and what remains uncertain is the
pre-event state, not the extent.

## 5. The maps

{{{{MAPS}}}}

## 6. What is still open for the maintainer

- The headline of the abstract, the conclusions and claims C01–C03 still carries A_new (all ground); switching to A_new,dry with
  ΔA_wet beside it is a decision, not a computation (T12h holds the numbers).
- Whether the p95x state mask and the ICEYE / UNOSAT diagnostic enter the paper (with coverage, chance level and admissible interval).
- The remaining UNOSAT-only flood on dry ground ({B(DRY, 'UNOSAT_only_km2', '.0f')} km², mostly our UNKNOWN at the water edge and in
  Oleshky / Hola Prystan) and our model-only water in the lowland south of Krynky (storage-sensitive).
- Literature values marked VERIFY in T16 (3616, 3623, Kadam et al. 2024) and the unread items of references_to_verify.md.
"""


def main():
    FM = _ld("fill_manuscript", HERE / "fill_manuscript.py")
    cache = {}

    def table(tid):
        if tid not in cache:
            cache[tid] = pd.read_csv(PT / f"{tid}.csv")
        return cache[tid]
    res = FM.make_resolver(table)
    inv = pd.read_csv(PT / "T01b.csv") if (PT / "T01b.csv").exists() else None

    def matrix(stratum):
        if inv is None:
            return "_T01b missing: run p95u and p96 first._"
        x = inv[(inv.stratum == stratum) & (inv.sensor != "UNOSAT")]
        M = x.pivot_table(index=["zone", "period"], columns="sensor", values="share_any_clear").reindex(columns=["S2", "S1_orb14", "S1_all", "k10e"])
        n = x.pivot_table(index=["zone", "period"], columns="sensor", values="n_scenes").reindex(columns=["S2", "S1_orb14", "S1_all", "k10e"])
        order = [p[0] for p in _ld("p95u", CS / "workflows" / "m6" / "p95u_evidence_inventory.py").PERIODS]
        lines = ["| zone | period | S2 | S1 orbit 14 | S1 all orbits | k10e |", "|---|---|---|---|---|---|"]
        for z in ("delta", "floodway", "inhulets"):
            for p in order:
                if (z, p) not in M.index:
                    continue
                cells = []
                for s_ in ("S2", "S1_orb14", "S1_all", "k10e"):
                    v, k = M.loc[(z, p), s_], n.loc[(z, p), s_]
                    cells.append("—" if pd.isna(v) else (f"**{v:.0%}** ({int(k)})" if v < MIN_SHARE else f"{v:.0%} ({int(k)})"))
                lines.append(f"| {z} | {p} | " + " | ".join(cells) + " |")
        return "\n".join(lines) + "\n\nshare of the stratum with a clear observation (number of scenes); **bold** = below the gate"

    def gaps():
        if inv is None:
            return "_T01b missing._"
        x = inv[(inv.stratum == "ALL") & (inv.sensor != "UNOSAT") & ((inv.n_scenes == 0) | (inv.share_any_clear < MIN_SHARE))]
        if x.empty:
            return "none"
        return "\n".join(f"- {r.zone} · {r.period} · {r.sensor}: {int(r.n_scenes)} scenes, clear {0 if pd.isna(r.share_any_clear) else r.share_any_clear:.0%} — {r.note}" for r in x.itertuples())

    def maps():
        rows = []
        for zone in ("delta", "floodway"):
            for stem, what in ((f"p95zm_{zone}_index_classes.png", "every Sentinel-2 index in display classes, cloud-free period composites before / after"),
                               (f"p95zm_{zone}_s1_vv.png", "Sentinel-1 VV orbit 14: spring median, 9 June (peak), 21 June"),
                               (f"p95zm_{zone}_k10e.png", "k10e surface classes on the best-covered dates"),
                               (f"p95z_{zone}_indices.png", "every index and the backscatter by stratum and day of year, 2022 vs 2023")):
                p = FIG / stem; rows.append(f"- {'✓' if p.exists() else '✗ missing'} `figures/m6_v003A/{stem}` — {zone}: {what}")
        for stem, what in (("p95y_difference_overview.png", "where ours and UNOSAT differ, on the Sentinel-1 change composite"),
                           ("p95y_difference_zooms.png", "the four windows of largest dry-ground disagreement"),
                           ("flood_dynamics_maps_s1.png", "Sentinel-1 new dark water per date (p94 diagnostic; FigS19 = the paper figure)"),
                           ("p95x_state_mask.png", "the daily state mask WATER / DRY / UNKNOWN and the transitions")):
            p = FIG / stem; rows.append(f"- {'✓' if p.exists() else '✗ missing'} `figures/m6_v003A/{stem}` — {what}")
        p = PUB / "figures" / "FigS19_s1_new_water_by_date.png"; rows.append(f"- {'✓' if p.exists() else '✗ missing'} `publication/figures/FigS19_s1_new_water_by_date.png` — the Sentinel-1 flood map by date in the paper")
        return "\n".join(rows)

    body = TEMPLATE.replace("{{MATRIX_ALL}}", matrix("ALL")).replace("{{MATRIX_WETLAND}}", matrix("GROUND_VEGETATED_WETLAND")).replace("{{GAPS}}", gaps()).replace("{{MAPS}}", maps())
    out = FM.PAT.sub(res, body)
    missing = sorted(set(__import__("re").findall(r"\[\[MISSING: ([^\]]+)\]\]", out)))
    (PUB / "WETLAND_EVIDENCE.md").write_text(out)
    (PT / "p96b_manifest.json").write_text(json.dumps(dict(producer="p96b_wetland_evidence.py", unresolved=missing, min_share=MIN_SHARE), indent=1))
    print(f"-> {PUB / 'WETLAND_EVIDENCE.md'} ({len(missing)} unresolved)")
    if missing:
        print("\n".join(missing)); raise SystemExit(1)


if __name__ == "__main__":
    main()
